### ISSUE TITLE
All data lost after changing timeformat

### ISSUE THREAD

**Issue by anoopd** [jrnl-org/jrnl#488]
I lost all my journal data once i added Week (%W) to the timeformat in  .jrnl_config . Is there a way to retrive the data  or is it lost for ever ? I reverted to the old timeformat but was not able to recover the data .

One more doubt is , will i be able to format ( say give colors to headings, lists ) as it is done for tags , say if we are using markdown tags ?

**Comment by maebert** [comment]
Hi @anoopd, in Jrnl 1.9x changing the time format for existing journals is not supported - check whether the actual journal file still contains data. This is fixed in the upcoming version 2.

What do you mean by markdown tags? Do you simply want to see a different color for headings?

**Comment by anoopd** [comment]
HI maebert, Thanks a lot for such a quick reply . I did checked the journal files and the data was not there ...... no probs , waiting for V2 . 

Yea i was thinking about simple formatting that would aid in distinguishing separate journal entries while viewing say a months journal .

**Comment by roryokane** [comment]
@anoopd Thanks for posting this issue. I wanted to change the time format, and was browsing the issue list when I saw your issue. If I hadn't seen it, I would have changed my `timeformat` without updating my `journal.txt` to match, and I would have lost all of my journal data.

I think this pitfall should be warned against in the `timeformat` bullet on the [Advanced Usage](http://jrnl.sh/advanced.html#configuration-file) documentation page, until version 2 is released.

**Comment by wren** [comment]
I just did this exact same thing. Luckily, I have backups, so no harm done.

I'm a bit saddened to see that there's mention of v2 from years ago but it apparently was never released. Is this project still updated, or is it dead?

**Comment by roryokane** [comment]
This issue is probably still relevant. Version 2 has not yet been released, so I assume the bug has not been fixed yet, and the `timeformat` description in the [Advanced Usage](http://jrnl.sh/advanced.html#configuration-file) documentation still doesn’t warn that changing it will delete all your existing entries that have a different time format.

**Comment by wren** [comment]
Hi! The stalebot got a bit overzealous with the backlog. Sorry about that! We'll need to go through and organize all the issues before turning it back on.

**Comment by wren** [comment]
@roryokane You can now install v2.0-rc2 via pip with this command: `pip install jrnl==2.0.0rc2`. It's a release candidate, so please report any bugs you run into. And, of course, make a backup, just in case!

The official v2.0 release is just around the corner!
